spring:
  liquibase:
    enabled: true
  datasource:
    username: finley
    password: password
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/books
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  rabbitmq:
    host: localhost
